apiVersion: apps/v1
kind: Deployment
metadata:
  name: colab-backend
  namespace: colab-app
  labels:
    app: colab-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: colab-backend
  template:
    metadata:
      labels:
        app: colab-backend
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
      volumes:
        - name: backend-secrets-vol
          secret:
            secretName: colab-backend-secret
            defaultMode: 400
