apiVersion: v1
kind: Pod
metadata:
  name: colab-app-backend-pods
  namespace: colab-app
  labels:
    app: colab-app-backend
spec:
  containers:
    - name: colab-backend-continer
      image: tekluman/colab-backend:v1.9.0
      ports:
        - containerPort: 5000
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /
          port: 5000
      env:
        - name: PORT
          value: "5000"
      envFrom:
        - secretRef:
            name: colab-backend-secret
      resources:
        limits:
          memory: "500Mi"
          cpu: "1"
        requests:
          memory: "500Mi"
          cpu: "500m"
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
