apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: colab-frontend-route
  namespace: teklu-soft-dev
spec:
  to:
    kind: Service
    name: frontend-service
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
